name: apunte-optimizacion-a2ic
channels:
  - conda-forge
dependencies:
  - python=3.11
  - nodejs=22
  - numpy=2
  - plotly=6
  - jupyterlab=4
  - ipykernel=7
  - poppler
  - pip
  - pip:
      - gurobipy==13.0.2
